version: "3"
services:
  react-app:
    image: myswr_image
    stdin_open: true
    ports:
      - "8080:8080"
    networks:
      - mern-app
  api-server:
    image: myswr_express_image
    ports:
      - "8888:8888"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge