version: '3'
services:
  front:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: react-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-network
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    container_name: express-container
    networks:
      - mern-stack-network
    volumes:
      - ./server:/app
networks:
  mern-stack-network: